name: Docker Build and Publish

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
      
    - name: login to GHCR
      uses: docker/login-action@v1
      with:
        registry: ghcr.io 
        username: ${{ github.actor }} 
        password: ${{ secrets.MY_GITHUB_TOKEN }}

    - name: Build and push Docker image
      run: |
        docker buildx build --platform linux/amd64,linux/arm64 -t ghcr.io/${{ github.repository_owner }}/${{ github.repository_name }}:latest .
        docker push ghcr.io/${{ github.repository_owner }}/${{ github.repository_name }}:latest
