name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build_and_upload:
    - name: Checkout project
      uses: actions/checkout@v2
      
    - name: Build image
      run: |
        # Use the official NGINX base image
        FROM nginx
        # Copy the NGINX configuration file with the custom capture-headers location
        COPY nginx.conf /etc/nginx/nginx.conf
        # Create a directory for the site content
        WORKDIR /usr/share/nginx/html
        # Create an index.html file (optional)
        RUN echo "Hello, NGINX!" > index.html
        # Expose port 80
        EXPOSE 80
        # Start NGINX
        CMD ["nginx", "-g", "daemon off;"]
        EOF

    - name: Upload image
      uses: ishworkh/container-image-artifact-upload@v1.0.0
      with:
        image: "test_image:latest"